### ISSUE TITLE
Commenting on locked nodes will fail

### ISSUE THREAD

**Issue by frankbolviken** [Alfresco/alfresco-ios-sdk#378]
Also, commenting as a collaborator on nodes will fail if it's the first comment posted (Don't have access to create the forum folder)

NSString * const kAlfrescoPublicAPIComments = @"nodes/{nodeRef}/comments";
This endpoint is invoked, and you will get the error.

As we investigated this, we found out that it works in our webapp because we use another rest endpoint:
"/service/api/node/{space}/{storeId}/{nodeId}/comments"
This endpoint works, because inside it disables behaviour checking.

So we have two endpoints which are supposed to do the same thing, but doing it in a slightly different way. 

We got around this by replacing the current with the above. Using the other endpoint for creating comments. Listing etc works perfectly.

**Comment by mikeh** [comment]
As this is a server-side issue, could you please mention which version of Alfresco you're using? Also if you could attach the error returned when the API call fails, that would be helpful.

Note: I don't think this should be patched in the SDK as Alfresco Cloud can only be accessed via the Public API - the underlying issue needs to be fixed rather than a workaround put in place on the mobile side.

**Comment by frankbolviken** [comment]
I agree with the server side fix. Thats why I didn't create any pull request for it :)
Alfresco Enterprise 4.2.3.6 is the version

The code fails in:
LockServiceImpl.java line 652
currentLockStatus is LOCK_OWNER
lockType is READ_ONLY_LOCK

**Comment by mikeh** [comment]
Thanks. I have raised the issue internally (MNT-14945).
